from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from core.config import get_settings
from routers import story, job
from db.database import create_tables

create_tables() # this is going to create our database tables based on our models that we have defined in our models folder and then we are going to be using this function to create our database tables when we run our application for the first time or when we make changes to our models and then we are going to be using alembic to manage our database migrations when we make changes to our models and then we are going to be using this function to create our database tables when we run our application for the first time or when we make changes to our models and then we are going to be using alembic to manage our database migrations when we make changes to our models
app = FastAPI(
    title = "Choose your own adventure API",
    description = "Api to  generate cool stories based on user input",
    version = "0.1.0", # and then  we are in production we could kind of update this versions every time we make a change to the codebase
    docs_url = "/docs",# this is going to be the url where we can access the swagger documentation for our api which is going to be automatically generated by fastapi based on the endpoints that we have defined in our codebase and the schemas that we have defined in our codebase and then we are also going to have a redocs url which is going to be another documentation for our api but it's going to be a little bit different from the swagger documentation and it's going to be more user friendly and it's going to be more interactive and it's going to be more visually appealing than the swagger documentation
    redoc_url = "/redocs"
)

# this is going to be the main entry point for our application and we are going to be using fastapi to create our api and we are going to be using uvicorn to run our api and we are going to be using pydantic to create our schemas and we are going to be using sqlalchemy to interact with our database and we are going to be using alembic to manage our database migrations and we are going to be using pytest to write our tests and we are going to be using docker to containerize our application and we are going to be using kubernetes to deploy our application and we are going to be using github actions to automate our deployment process
app.add_middleware(
    CORSMiddleware, # what this is going to allow us to do is have our api be used from a different origin to essentialy or the domain that you are running  these services on so for example if you are running your frontend on localhost 3000 and your backend on localhost 8000 this is going to allow you to make requests from the frontend to the backend without any issues with cors which is a security feature that browsers have implemented to prevent malicious websites from making requests to other websites on behalf of the user
    allow_origins = get_settings().allowed_origins_list, # this is going to allow all origins to make requests to our api but in production you might want to be more specific and only allow certain origins to make requests to your api
    allow_credentials = True, # this is going to allow cookies to be sent with requests to our api which is important for authentication and session management
    allow_methods = ["*"], # this is going to allow all methods to be used when making requests to our api but in production you might want to be more specific and only allow certain methods to be used when making requests to your api post get put delete patch options head etc
    allow_headers = ["*"] # this is going to allow all headers to be sent with requests to our api but in production you might want to be more specific and only allow certain headers to be sent with requests to your api    
)


app.include_router(story.router, prefix= get_settings().API_PREFIX) # this is going to include the story router in our app and then we are going to be able to access the endpoints that we have defined in our story router by going to the url that we have defined in our story router for example if we have defined a create story endpoint in our story router with the url /create then we are going to be able to access that endpoint by going to localhost 8000/api/stories/create because we have defined the prefix for our story router as /stories and then we have defined the prefix for our api as /api so it's going to be localhost 8000/api/stories/create
app.include_router(job.router, prefix= get_settings().API_PREFIX) # this is going to include the job router in our app and then we are going to be able to access the endpoints that we have defined in our job router by going to the url that we have defined in our job router for example if we have defined a get job status endpoint in our job router with the url /{job_id} then we are going to be able to access that endpoint by going to localhost 8000/api/jobs/{job_id} because we have defined the prefix for our job router as /jobs and then we have defined the prefix for our api as /api so it's going to be localhost 8000/api/jobs/{job_id}
# we are going to be importing our routers here and then we are going to be including them in our app so that we can have our api endpoints organized in different files and then we are going to be importing our database session here and then we are going to be using it in our endpoints to interact with our database
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host = "localhost", port = 8000, reload = True) # this is going to run our api on localhost 8000 and the reload option is going to allow us to see changes in our code without having to restart the server every time we make a change to our codebase)
